Update Orb to include inline scanner (#30)
* [semver:1.3.0]

* First pass lw scanner

* Inline scan

* Inline scan

* Update integration test

* Update integration test

* Update integration test

* First pass at triggering scan

* Remove scan

* Remove scan

* Remove scan

* Remove scan

* Update params

* Update params

* Update scan command

* Add additional param

* add more params

* New test

* Include more parameters

* Moar params

* Moar params

* Update conf

* Add install script to repo and additional params

* update params

* Add new example

* Update params...again

* Output HTML vuln report

* remve extraneous param

* superflous params

* superflous params

* remove superflous file

* Update integration test

* Add params for exit codes

* update default params

* set defaults

* update script

* fix typo

* Update naming convention

* naming...

* naming...

* update names...again

* fail build

* remove extra params

Co-authored-by: Chris Black <chris.black@lacework.net>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,6 +28,48 @@ jobs:
               exit 1
             fi
 
+  integration-test-install-inline-scanner:
+    executor: orb-tools/ubuntu
+    steps:
+      - checkout
+      - lacework/install-inline-scanner
+      - run:
+          name: Verify install
+          command: |
+            if ! lw-scanner version; then
+              echo "The lacework inline scanner was not found"
+              exit 1
+            fi
+
+  integration-test-execute-inline-evaluation:
+    working_directory: ~/project
+    machine: true
+    steps:
+      - checkout
+      - lacework/install-inline-scanner
+      - run:
+          name: Pull in vuln image for testing
+          command: |
+            docker pull chriscircleci/vuln_django:7f7305bea884b63578c28d4513a916e2247ec152
+      - lacework/inline-scanner-evaluate:
+          image_tag: "7f7305bea884b63578c28d4513a916e2247ec152"
+          image_name: "chriscircleci/vuln_django"
+          html: true
+          tags: "orb_test=true"
+          save: true
+          data-directory: ~/project/vuln_report
+      - run:
+          command: |
+            mkdir  lacework-artifacts/
+
+            if [ `ls -1 lacework-lacework-cli* 2>/dev/null | wc -l ` -gt 0 ]; then
+                mv lacework-lacework-cli* lacework-artifacts/
+            fi
+
+      - store_artifacts:
+          path: lacework-artifacts
+
+
   integration-test-ctr-vuln-scan:
     executor: lacework/default
     steps:
@@ -155,11 +197,13 @@ workflows:
     when: << pipeline.parameters.run-integration-tests >>
     jobs:
       - integration-test-install-cli
+      - integration-test-install-inline-scanner
       - integration-test-ctr-vuln-scan
       - integration-test-scan-pkg-manifest
       - integration-test-ctr-vuln-scan-fail_on_fixable
       - integration-test-ctr-vuln-scan-show-only-fixable
       - integration-test-ctr-vuln-scan-fail-on-severity
+      - integration-test-execute-inline-evaluation
 
       # Test multiple permutations of the job abstraction
       - lacework/ctr-vuln-scan:
